name: Publish Cucumber HTML Report to GitHub Pages
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  publish-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages (gh-pages) using PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./target/cucumber-reports
          publish_branch: gh-pages
