name: Publish Cucumber HTML Report to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Google Chrome and matching Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6
      
          # Install a specific Chrome version (example: 127.x). Change CHROME_VERSION as needed.
          CHROME_VERSION=127.0.0
          # Use browser-actions/setup-chrome action instead if preferred
      
          # If you can use apt pinning (if package version available), otherwise use the official .deb
          wget -q -O /tmp/google-chrome-stable_current_amd64.deb \
            https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
      
          # Determine major version from installed chrome and download matching chromedriver
          CHROME_MAJOR=$(google-chrome --version | sed -E 's/.* ([0-9]+)\..*/\1/')
          echo "Chrome major version: $CHROME_MAJOR"
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR)
          echo "Using chromedriver version: $CHROMEDRIVER_VERSION"
      
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P /tmp
          sudo unzip -o /tmp/chromedriver_linux64.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver
      
          google-chrome --version || true
          chromedriver --version || true

      - name: Start Xvfb (display) for browsers if needed
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 & 
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Maven tests (generate cucumber report)
        run: mvn -B test

      - name: Ensure report folder exists
        run: |
          if [ ! -d "target/cucumber-reports" ]; then
            echo "Report folder target/cucumber-reports not found"
            ls -la target || true
            exit 1
          fi
          echo "Found report folder, contents:"
          ls -la target/cucumber-reports || true

      - name: Deploy to GitHub Pages (gh-pages) using PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./target/cucumber-reports
          publish_branch: gh-pages
