name: Publish Cucumber HTML Report to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6
          # Install Google Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Install latest Chromedriver
          LATEST=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip -P /tmp
          sudo unzip -o /tmp/chromedriver_linux64.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver
          # show versions
          google-chrome --version || true
          chromedriver --version || true

      - name: Start Xvfb (display) for browsers if needed
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 & 
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Maven tests (generate cucumber report)
        run: mvn -B test

      - name: Ensure report folder exists
        run: |
          if [ ! -d "target/cucumber-reports" ]; then
            echo "Report folder target/cucumber-reports not found"
            ls -la target || true
            exit 1
          fi
          echo "Found report folder, contents:"
          ls -la target/cucumber-reports || true

      - name: Deploy to GitHub Pages (gh-pages) using PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./target/cucumber-reports
          publish_branch: gh-pages
