name: Publish Cucumber HTML Report to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # ✅ Install Chrome only (WebDriverManager handles chromedriver)
      - name: Install Google Chrome (via browser-actions)
        uses: browser-actions/setup-chrome@v2
        with:
            chrome-version: latest          # or a specific major like 127
            install-dependencies: true      # installs required OS deps on Linux
            install-chromedriver: false

      - name: Start Xvfb (display) for browsers
        run: |
          Xvfb :99 -screen 0 1920x1080x24 >/dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      # ✅ NEW: set CHROME_ARGS so your DriverFactory runs headless
      - name: Set CHROME_ARGS for headless Chrome in CI
        run: |
          echo "CHROME_ARGS=--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080 --disable-software-rasterizer" >> $GITHUB_ENV

      # ✅ Run Maven tests and save output
      - name: Run Maven tests (generate cucumber report)
        run: mvn -B -e test | tee mvn.log

      # ✅ (Optional) upload logs/reports for debugging
      - name: Upload Maven logs and test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            mvn.log
            target/surefire-reports
            target/cucumber-reports

      - name: Ensure report folder exists
        run: |
          if [ ! -d "target/cucumber-reports" ]; then
            echo "❌ Report folder target/cucumber-reports not found!"
            ls -la target || true
            exit 1
          fi
          echo "✅ Found report folder, contents:"
          ls -la target/cucumber-reports || true

      # ✅ Publish cucumber report to GitHub Pages
      - name: Deploy to GitHub Pages (gh-pages) using PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./target/cucumber-reports
          publish_branch: gh-pages
